#!/bin/bash -e
#
#Instalar entorno de programación

DEF_USER=test

apt-get -y install lib32stdc++6
cd $HOME
sudo -u $DEF_USER wget https://dl.google.com/dl/android/studio/ide-zips/2.3.3.0/android-studio-ide-162.4069837-linux.zip
sudo -u $DEF_USER unzip android-studio-ide-162.4069837-linux.zip
mv android-studio /opt/
sudo -u $DEF_USER /opt/android-studio/bin/studio.sh

#instalar oracle java
add-apt-repository ppa:webupd8team/java
apt-get update
echo 'oracle-java8-installer shared/accepted-oracle-license-v1-1 boolean true' | debconf-set-selections
apt-get install oracle-java8-set-default
apt-get install oracle-java8-installer

#instalar eclipse
apt-get install eclipse eclipse-cdt eclipse-cdt-autotools eclipse-emf eclipse-gef eclipse-pydev eclipse-wtp eclipse-wtp-servertools eclipse-wtp-webtools \
	gradle libautocomplete-java maven \
	festival festival-doc festival-freebsoft-utils festvox-ellpc11k speech-dispatcher-festival speech-tools

