#!/bin/sh -e
#export DEF_USER=test
#enketo
#ntpdate
#sudo apt-get install -y software-properties-common dirmngr 
#sudo add-apt-repository -y ppa:chris-lea/redis-server
apt-get update
apt-get upgrade -y

#detener apache2 primero
systemctl disable apache2
systemctl stop apache2

apt-get install -y git nginx-extras htop build-essential redis-server checkinstall python

curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
apt-get install -y nodejs
#grunt-jsbeautifier grunt-concurrent grunt-contrib-jshint grunt-contrib-watch grunt-karma grunt-mocha-test grunt-nodemon
npm install -g grunt-cli pm2

dpkg-reconfigure -plow -f noninteractive unattended-upgrades
#debconf unattended-upgrades
echo	unattended-upgrades	unattended-upgrades/origins_pattern	string	"origin=Debian,codename=${distro_codename},label=Debian-Security" | debconf-set-selections
echo	unattended-upgrades	unattended-upgrades/enable_auto_updates	boolean	true | debconf-set-selections

cd ~
sudo -u $DEF_USER git clone https://github.com/enketo/enketo-express.git
cd enketo-express
sudo -u $DEF_USER npm install --production

systemctl stop redis

mv /etc/redis/redis.conf /etc/redis/redis-origin.conf
cp ~/enketo-express/setup/redis/conf/redis-enketo-main.conf /etc/redis/
cp ~/enketo-express/setup/redis/conf/redis-enketo-cache.conf /etc/redis/

cp ~/enketo-express/setup/redis/systemd/system/* /etc/systemd/system/

systemctl disable redis
systemctl daemon-reload
systemctl start redis@redis-enketo-main
systemctl enable redis@redis-enketo-main
systemctl start redis@redis-enketo-cache
systemctl enable redis@redis-enketo-cache

#cp ~/enketo-express/config/default-config.json ~/enketo-express/config/config.json
#configurar
cp ~/scripts/config.json ~/enketo-express/config/config.json

sudo -u $DEF_USER grunt

#npm start

sudo -u $DEF_USER pm2 start app.js -n enketo
sudo -u $DEF_USER pm2 save
#-u test/enketo
pm2 startup -u $DEF_USER --hp ~

#crear webserver conf
#cat /etc/nginx/sites-available/enketo
cp ~/scripts/enketo /etc/nginx/sites-available/enketo
#activar
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/enketo /etc/nginx/sites-enabled/enketo 
service nginx restart

#reiniciar después de modificar conf.json -> grunt -> pm2 restart enketo

#configurar api aggregate
#url = http:...:8888/api/v1/

