#!/bin/bash -e
#
#Instala Enketo

#export DEF_USER=test
#SCRIPTS=~/scripts
echo "$(tput bold)Instalando Enketo$(tput sgr0)" | tee $PS_LOG/enketo-install

#sudo apt-get install -y software-properties-common dirmngr 
#sudo add-apt-repository -y ppa:chris-lea/redis-server
apt-get update
apt-get upgrade -y

#detener apache2 primero
#(systemctl disable apache2 && systemctl stop apache2 && \
#echo 'Se ha detenido el servidor Apache' || echo 'No se ha podido detener Apache') > $PS_LOG/enketo-install

apt-get install -y git nginx-extras htop build-essential redis-server checkinstall python | tee -a $PS_LOG/enketo-install

curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
echo 'Instalando node.js' | tee -a $PS_LOG/enketo-install
apt-get install -y nodejs
#grunt-jsbeautifier grunt-concurrent grunt-contrib-jshint grunt-contrib-watch grunt-karma grunt-mocha-test grunt-nodemon
npm install -g grunt-cli pm2 | tee -a $PS_LOG/enketo-install

dpkg-reconfigure -plow -f noninteractive unattended-upgrades
#debconf unattended-upgrades
echo	unattended-upgrades	unattended-upgrades/origins_pattern	string	"origin=Debian,codename=${distro_codename},label=Debian-Security" | debconf-set-selections
echo	unattended-upgrades	unattended-upgrades/enable_auto_updates	boolean	true | debconf-set-selections

echo 'Instalando enketo-express' | tee -a $PS_LOG/enketo-install
cd ~
sudo -u $DEF_USER git clone https://github.com/enketo/enketo-express.git
cd enketo-express
sudo -u $DEF_USER npm install --production

systemctl stop redis

echo 'Instalando Redis' | tee -a $PS_LOG/enketo-install
mv /etc/redis/redis.conf /etc/redis/redis-origin.conf
cp ~/enketo-express/setup/redis/conf/redis-enketo-main.conf /etc/redis/
cp ~/enketo-express/setup/redis/conf/redis-enketo-cache.conf /etc/redis/
cp ~/enketo-express/setup/redis/systemd/system/* /etc/systemd/system/

systemctl disable redis && systemctl daemon-reload
systemctl start redis@redis-enketo-main && systemctl enable redis@redis-enketo-main
systemctl start redis@redis-enketo-cache && systemctl enable redis@redis-enketo-cache
echo 'Redis configurado' >> $PS_LOG/enketo-install
ls -l /etc/redis >> $PS_LOG/enketo-install

#cp ~/enketo-express/config/default-config.json ~/enketo-express/config/config.json
#configurar enketo
cp $SCRIPTS/config.json ~/enketo-express/config/config.json

echo 'Configurando enketo-express' | tee -a $PS_LOG/enketo-install
sudo -u $DEF_USER grunt

#npm start

echo 'Instalando servicio'
sudo -u $DEF_USER pm2 start app.js -n enketo
sudo -u $DEF_USER pm2 save
#-u test/enketo
(pm2 startup -u $DEF_USER --hp ~ && \
echo 'Se ha configurado el servicio' || echo 'Error al configurar el servicio') >> $PS_LOG/enketo-install

#copiar logo
#cp $SCRIPTS/COLOR-01.png $HOME/enketo-express/public/images/logo.png

#crear webserver conf
#cat /etc/nginx/sites-available/enketo
#cp ~/scripts/enketo /etc/nginx/sites-available/enketo
#proxy completo
#cp ~/scripts/tomcat-proxy.conf /etc/nginx/sites-available/tomcat-proxy.conf
#activar
#rm /etc/nginx/sites-enabled/default
#ln -s /etc/nginx/sites-available/enketo /etc/nginx/sites-enabled/enketo 
#ln -s /etc/nginx/sites-available/tomcat-proxy.conf /etc/nginx/sites-enabled/tomcat-proxy.conf
#service nginx restart

#configurar proxy completo
(sh $SCRIPTS/proxy-install tomcat-proxy.conf && \
echo 'Se ha configurado el proxy' || echo 'Error al configurar el proxy') >> $PS_LOG/enketo-install

apt-get install -y fail2ban
cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
service fail2ban restart

#configurar firewall
#ufw allow ssh
#ufw allow 80
#ufw allow 443
#ufw enable
#ufw status

#reiniciar después de modificar conf.json -> grunt -> pm2 restart enketo

#configurar api aggregate
#url = http://ejemplo.com:8080/api/v1/
#c/ proxy: http://ejemplo.com/enketo/api/v1
