#!/bin/sh -e

mkdir /usr/local/etc/geoportal
export GEO=/usr/local/etc/geoportal
mkdir /usr/local/etc/lucene
mkdir /usr/local/etc/lucene/assertion
ls /usr/local/etc > $PS_LOG/geo

adduser geoportal --gecos "" --disabled-password
echo "geoportal:password" | sudo chpasswd
addgroup geoportal sudo
#su geoportal
cd $GEO
wget https://github.com/Esri/geoportal-server/releases/download/v1.2.8/geoportal-1.2.8.zip
unzip geoportal-1.2.8.zip
ls -l >> $PS_LOG/geo

cd $GEO'/Database Scripts'
chown -R postgres:postgres $GEO'/Database Scripts/PostgreSQL'
chmod -R +x $GEO'/Database Scripts/PostgreSQL'
cd $GEO'/Database Scripts/PostgreSQL'
ls -l >> $PS_LOG/geo

dos2unix grants_linuxpg.sh
dos2unix grants_pg.sql
dos2unix create_schema_linuxpg.sh
dos2unix schema_pg.sql

#agregar contraseña postgres
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" >> $PS_LOG/geo
sudo su postgres grants_linuxpg.sh localhost 5432 postgres geoportal postgres geoportal 
sudo su postgres create_schema_linuxpg.sh localhost 5432 postgres geoportal
sudo -u postgres psql -c "\dn" >> $PS_LOG/geo
sudo -u postgres psql -c "\dtvs geoportal.*" >> $PS_LOG/geo

cp $GEO'/Web Applications/Geoportal/geoportal.war' $TOMCAT_APPS
systemctl restart postgresql
systemctl restart tomcat8
mv $TOMCAT_APPS/geoportal/WEB-INF/classes/gpt/config/gpt.xml $TOMCAT_APPS/geoportal/WEB-INF/classes/gpt/config/gpt.xml.old
cp ~/scripts/gpt.xml $TOMCAT_APPS/geoportal/WEB-INF/classes/gpt/config/gpt.xml
chown tomcat8:tomcat8 $TOMCAT_APPS/geoportal/WEB-INF/classes/gpt/config/gpt.xml

cp ~/scripts/geoportal.xml /etc/tomcat8/Catalina/localhost/geoportal.xml
chown root:tomcat8 /etc/tomcat8/Catalina/localhost/geoportal.xml
#sudo chmod +wx geoportal.xml