#!/bin/bash -e
#
#configurar proxy

#SCRIPTS=~/scripts

NEW_CONF=$1
OLD_CONF=$2
 
#configurando nginx
echo "$(tput bold)Configurando nginx$(tput sgr0)"

if [ -z $NEW_CONF ]; then
	nginx -t && nginx -s reload
	else
#cp ~/scripts/tomcat-proxy.conf /etc/nginx/sites-available/tomcat-proxy.conf && \
#rm /etc/nginx/sites-enabled/default && \
#ln -s /etc/nginx/sites-available/tomcat-proxy.conf /etc/nginx/sites-enabled/tomcat-proxy.conf 

cp $SCRIPTS/$NEW_CONF /etc/nginx/sites-available && \
rm /etc/nginx/sites-enabled/$OLD_CONF && \
ln -s /etc/nginx/sites-available/$NEW_CONF /etc/nginx/sites-enabled

(nginx -t && nginx -s reload && \
echo "$NEW_CONF : configuración exitosa" || echo "error al configurar $NEW_CONF") >> $PS_LOG/proxy-install
fi
exit




