#!/bin/bash -e
#
#Actualizar preseed.conf

echo "$(tput bold)Configurando usuarios preseed.cfg$(tput sgr0)"
read -p "Usuario: " us
us=${us:-admin}
read -p "Nombre completo: " nom
nom=${nom:-$us}
read -p "Nombre del host: " hn
hn=${hn:-debian}
read -p "contraseña: " pass
pass=${pass:-admin}

read -p "¿Instalar mediante USB?: " pusb
pusb=${pusb:-}

if [ -z $pusb ]; then
	metod=URL 
	read -p "scripts URL: " scurl
	scurl=${scurl:-192.168.56.101/preseed}
	#sedvar=s,wget http://.*/rc.local,wget http://'"$scurl"'/rc.local,
	sedvar="wget http://"$scurl"/rc.local -P"
else
	metod=USB
	sedvar="cp /media/rc.local"
fi 
rnum=$(shuf -i 500000-5000000 -n 1)
pwd=$(mkpasswd -R $rnum -m sha-512 "$pass")
echo "mi us: $us \nmi nom: $nom \nmi pass: $pass \nmi pwd: $pwd \nmi host: $hn \nmi url: $scurl"

(sed -i.old -e 's/d-i passwd\/username string .*/d-i passwd\/username string '"$us"'/' \
	-e 's/d-i passwd\/user-fullname string .*/d-i passwd\/user-fullname string '"$nom"'/' \
	-e 's,.* passwd/user-password-crypted password .*,d-i passwd/user-password-crypted password '"$pwd"',' \
	-e '/d-i passwd\/user-password password .*/s/^/#/' \
	-e '/d-i passwd\/user-password-again password .*/s/^/#/' \
	-e '/^#/! s,d-i netcfg/get_hostname string .*,d-i netcfg/get_hostname string '"$hn"',' \
	-e '/Post-install/ a #Instalando mediante '"$metod"'' \
	-e 's|wget http://.*/rc.local -P|'"$sedvar"'|' preseed.cfg && \
echo 'Se ha actualizado preseed.cfg' || echo 'ha ocurrido un error') 

#	funciona sólo si la linea está comentada
#	-e 's,\#d-i passwd/user-password-crypted password \[crypt(3) hash\],d-i passwd/user-password-crypted password '"$pwd"',' \

#	funcionan 
#	-e 's,.* passwd/user-password-crypted password .*,d-i passwd/user-password-crypted password '"$pwd"',' \

#	modifica todas las lineas coincidentes
#	-e 's,d-i netcfg/get_hostname string .*,d-i netcfg/get_hostname string '"$hn"',' \

#	funciona pero no borra espacios en blanco probar /^# / ó /^#./ 	
#	-e '/d-i passwd\/user-password-crypted password .*/ s/^#//; s,d-i passwd/user-password-crypted password .*,d-i passwd/user-password-crypted password '"$pwd"',' \
	
#	-e '/^#/ s,d-i passwd/user-password-crypted password .*,d-i passwd/user-password-crypted password '"$pwd"',' \

#-e 's,wget http://.*/rc.local,wget http://'"$scurl"'/rc.local,'

#modificar rc.local
(sed -i.old -e 's/export DEF_USER=.*/export DEF_USER='"$us"'/' rc.local && \
echo 'Se ha actualizado rc.local' || echo 'ha ocurrido un error') 

