#!/bin/sh -e
#
# Instalar servidor base

#export DEBIAN_FRONTEND=noninteractive
export DEF_USER=user
export DEF_PATH=/home/$DEF_USER
mkdir $DEF_PATH/pslog
export PS_LOG=$DEF_PATH/pslog

apt-get update | tee $PS_LOG/update
apt-get upgrade | tee -a $PS_LOG/update
apt-get dist-upgrade | tee -a $PS_LOG/update
apt-get install -y git

git clone 'https://github.com/git-terbug/scripts.git' $DEF_PATH/scripts | tee -a $PS_LOG/update
cd $DEF_PATH/scripts && chmod 744 *-install geoportal.xml *-setup tomngr ngx 
#&& chmod -x gpt.xml config.json enketo server.xml tomcat-users.xml test.jsp
#ln -s $DEF_PATH/scripts/serv-setup $DEF_PATH

##instalando phppgadmin
#echo 'Instalando phppgadmin'
#apt-get install -q -y phppgadmin
# | tee -a $PS_LOG/phppgadmin-ps
#echo 'phppgadmin instalado'
# >> $PS_LOG/phppgadmin-ps
#systemctl start php7.0-fpm && systemctl enable php7.0-fpm 
#ln -s /usr/share/phppgadmin /var/www/html

#instalar servidor
echo 'Instalando paquetes' | tee $PS_LOG/servidor_base
apt-get install -q -y php php-intl default-jdk links \
	postgresql postgresql-contrib php-pgsql php-fpm php7.0-fpm 
	dos2unix curl zip unrar nginx nginx-full nginx-extras
#ntp ntpdate whois ufw geany efte \
#	r-base r-cran-rjava r-cran-postgresql r-cran-shiny postgis postgis-gui libpostgis-java \
echo 'Instalando tomcat' | tee $PS_LOG/tomcat-ps

#apt-get update | tee -a $PS_LOG/tomcat-ps
apt-get install -q -y tomcat8 tomcat8-admin tomcat8-user tomcat8-common libtomcat8-java \
	libtcnative-1 libapache2-mod-apreq2 libapreq2-3 libservlet3.1-java \
	libapache-pom-java libjasperreports-java libcommons-logging-java libapache2-mod-jk \
	libpostgresql-jdbc-java | tee -a $PS_LOG/tomcat-ps  

#copiar el controlador adecuado
echo '/usr/share/tomcat8/lib' | tee -a $PS_LOG/tomcat-ps
#ln -s /usr/share/java/mysql-connector-java.jar /usr/share/tomcat8/lib/mysql-connector-java.jar |tee -a $PS_LOG/tomcat-ps
ln -s /usr/share/java/postgresql.jar /usr/share/tomcat8/lib
ls /usr/share/tomcat8/lib | tee -a $PS_LOG/tomcat-ps

#configurando opciones
#echo 'export CATALINA_OPTS="$CATALINA_OPTS -Xms256m"' > /usr/share/tomcat8/bin/setenv.sh
#echo 'export CATALINA_OPTS="$CATALINA_OPTS -Xmx512m"' >> /usr/share/tomcat8/bin/setenv.sh
#echo 'export CATALINA_OPTS="$CATALINA_OPTS -XX:PermSize=512m"' >> /usr/share/tomcat8/bin/setenv.sh
#echo 'export CATALINA_OPTS="$CATALINA_OPTS -XX:MaxPermSize=512m"' >> /usr/share/tomcat8/bin/setenv.sh
cp $DEF_PATH/scripts/setenv.sh /usr/share/tomcat/bin/setenv.sh
chmod +x /usr/share/tomcat8/bin/setenv.sh
cat /usr/share/tomcat8/bin/setenv.sh | tee -a $PS_LOG/tomcat-ps

#crear directorios faltantes
mkdir -p /usr/share/tomcat8/{common,shared,sever}/classes 

echo 'configurar manager app'
./tomngr

echo 'tomcat instalado' >> $PS_LOG/tomcat-ps

echo "contenido $DEF_PATH/scripts" | tee -a $PS_LOG/servidor_base
ls -l $DEF_PATH/scripts | tee -a $PS_LOG/servidor_base
chown -R $DEF_USER:$DEF_USER $PS_LOG

exit 0
