#!/bin/bash -e
#
#Instala los componentes necesarios del servidor
#ejecutar sh serv-setup

export DEF_USER=$USER
export PS_LOG=~/pslog
export TOMCAT_APPS=/var/lib/tomcat8/webapps

#echo "\033[1mInstalando componentes\033[0m" #negritas ANSI
echo "$(tput bold)Instalando componentes$(tput sgr0)"
#echo 'Instalando ODK Aggregate'
#sudo -E sh ~/scripts/aggregate-install
#echo 'Instalando Enketo'
#sudo -E sh ~/scripts/enketo-install
#echo 'Instalando Geoportal'
#sudo -E sh ~/scripts/geoportal-install

#ejecutar sudo -E sh serv-setup
#asignar usuario manualmente
export DEF_USER=$1
#export DEF_PATH=/home/$DEF_USER
cd ~/scripts
#sh ~/scripts/aggregate-install && sh ~/scripts/enketo-install && sh ~/scripts/geoportal-install
#ejecutables
./tomngr && ./aggregate-install && ./enketo-install && ./geoportal-install
#sh hola && sudo -E sh hola && sh echo $HOME && sh false && sh echo bye

exit 0
