#!/bin/sh -e
#mkdir /usr/local/etc/hola
echo $DEF_USER
exit
#env	|	less
echo $HOME/hola 
echo $LOGNAME
sudo mkdir /usr/local/etc/mundo
sudo echo ~
#sudo env	|	less
echo $USER/mundo
cd $HOME
cd ~
ls
sudo -E -u $USER sh ~/scripts/hola
sudo -u $USER sh ~/scripts/hola
sudo -E sh ~/scripts/hola
