#!/bin/bash -e

echo 'Creando certificado'
#openssl genrsa -out /etc/ssl/private/server.key 4096
#openssl req -new -key /etc/ssl/private/server.key -out /etc/nginx/ssl/server.csr

#self-signed
openssl req -x509 -nodes -days 365 -config scert.cnf -newkey rsa:4096 -keyout /etc/ssl/private/test.key -out /etc/ssl/private/test.crt
openssl dhparam -out /etc/ssl/private/dhparam.pem 4096

#export
openssl pkcs12 -export -in /etc/ssl/private/test.crt -inkey /etc/ssl/private/test.key -out /etc/ssl/private/test.pfx
chmod 644 /etc/ssl/private/test.pfx

#configurar tomcat
'Configurando tomcat'
sed -i  '/<!-- Define an AJP/ i <Connector port="8443" protocol="HTTP/1.1"
               maxThreads="150" SSLEnabled="true" secure="true" scheme="https" 
		clientAuth="false" sslProtocol="TLS"
		keystoreFile="/etc/nginx/ssl/test.pfx" 
		keystoreType="PKCS12"
   		keystorePass="password" />' /etc/tomcat8/server.xml

systemctl restart tomcat8 

#configurar nginx
echo 'Configurando nginx'
cp ~/scripts/tomcat-ssl.conf /etc/nginx/sites-available/tomcat-ssl.conf && \
rm /etc/nginx/sites-enabled/tomcat-proxy.conf && \
ln -s /etc/nginx/sites-available/tomcat-ssl.conf /etc/nginx/sites-enabled/tomcat-ssl.conf 
cp ~/scripts/ssl-cert.conf /etc/nginx/snippets/ssl-cert.conf
cp ~/scripts/ssl-params.conf /etc/nginx/snippets/ssl-params.conf
nginx -t && nginx -s reload